/**
 * Taking a version that requires `revision_form` must not fail on adoption.
 *
 * Every review pack already on disk lacks the marker, so without a migration
 * the first `validate --fail-on error` after the upgrade reports each of them as
 * a blocking `QFAI-REVIEW-007` — a condition no producer can go back and fix,
 * because the tree each of those verdicts described is no longer
 * reconstructible. The classification the upgrade can still make is exactly the
 * one recorded here: a pack that does not declare the form was written before
 * the form existed.
 */

import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { migrateLegacyReviewPacks } from "../../src/core/doctor/migrateLegacyReviewPacks.js";
import { validateReviewArtifacts } from "../../src/core/validators/reviewArtifacts.js";

const tempDirs: string[] = [];

afterEach(async () => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) await rm(dir, { recursive: true, force: true });
  }
});

async function seedPack(root: string, stamp: string, summary: Record<string, unknown>) {
  const packDir = path.join(root, ".qfai", "review", `review-${stamp}`);
  await mkdir(packDir, { recursive: true });
  await writeFile(path.join(packDir, "review_request.md"), "# request\n", "utf-8");
  await writeFile(path.join(packDir, "R01_completion-reviewer.md"), "# review\n", "utf-8");
  await writeFile(path.join(packDir, "summary.json"), JSON.stringify(summary, null, 2), "utf-8");
}

const undeclared = {
  version: "1.0",
  created_at: "2026-01-01T00:00:00Z",
  target: { kind: "spec", path: ".qfai/specs/spec-0001" },
  overall_status: "PASS",
  roster: [{ reviewer: "completion-reviewer", status: "PASS", feedback_count: 0 }],
};

async function newRoot(): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), "qfai-legacy-migrate-"));
  tempDirs.push(root);
  return root;
}

describe("legacy review pack migration", () => {
  it("records every pack that does not declare the form", async () => {
    const root = await newRoot();
    await seedPack(root, "20260101000000000", undeclared);
    await seedPack(root, "20260102000000000", { ...undeclared, revision_form: "content-hash" });

    const result = await migrateLegacyReviewPacks(root);

    expect(result.added).toEqual(["review-20260101000000000"]);
    const written = await readFile(result.manifestPath, "utf-8");
    expect(written).toContain("review-20260101000000000");
    expect(written).not.toContain("review-20260102000000000");
  });

  it("clears the blocking findings the upgrade would otherwise produce", async () => {
    const root = await newRoot();
    await writeFile(
      path.join(root, ".gitignore"),
      "# ── QFAI managed (generated by qfai init) ──\n.qfai/review/*\n",
      "utf-8",
    );
    await seedPack(root, "20260101000000000", {
      ...undeclared,
      revision: "working-tree+9f2c1ab",
    });

    const before = await validateReviewArtifacts(root);
    expect(before.some((i) => i.code === "QFAI-REVIEW-007")).toBe(true);

    // Both halves of the same fact, written by the migration: the manifest, and
    // the pack marker the validator checks it against. Writing only one left
    // every pack a blocking finding — the state this exists to clear.
    const result = await migrateLegacyReviewPacks(root);
    expect(result.marked).toEqual(["review-20260101000000000"]);

    const after = await validateReviewArtifacts(root);
    expect(after.some((i) => i.code === "QFAI-REVIEW-007")).toBe(false);
    expect(after.some((i) => i.code === "QFAI-REVIEW-009")).toBe(true);
  });

  it("is additive and idempotent", async () => {
    const root = await newRoot();
    await seedPack(root, "20260101000000000", undeclared);
    await mkdir(path.join(root, ".qfai", "review"), { recursive: true });
    await writeFile(
      path.join(root, ".qfai", "review", ".legacy-packs"),
      "# kept\nreview-19990101000000000\n",
      "utf-8",
    );

    await migrateLegacyReviewPacks(root);
    const second = await migrateLegacyReviewPacks(root);

    // A repeat run adds nothing, and a name an operator recorded by hand is
    // never dropped.
    expect(second.added).toEqual([]);
    const written = await readFile(path.join(root, ".qfai", "review", ".legacy-packs"), "utf-8");
    expect(written).toContain("review-19990101000000000");
    expect(written).toContain("review-20260101000000000");
  });

  it("writes nothing under dry-run", async () => {
    const root = await newRoot();
    await seedPack(root, "20260101000000000", undeclared);

    const result = await migrateLegacyReviewPacks(root, { dryRun: true });

    expect(result.added).toEqual(["review-20260101000000000"]);
    await expect(readFile(result.manifestPath, "utf-8")).rejects.toThrow();
  });
});
