/**
 * E2E test traceability index for spec-0012 v1.7.16 (US-0012-0084..0093)
 *
 * Historical `it.todo` stubs were resolved during the spec-0017 rollout.
 * Each user story below is either covered by an executing unit / integration
 * test, or its underlying gate was superseded by spec-0017.
 *
 * -------------------------------------------------------------------------
 * US-0012-0084 — Delegation Scope Table routing
 *   Covered by: tests/skill/prototypingSkillV1716.test.ts (TC-0012-0285)
 *
 * US-0012-0085 — full-harness iteration gate enforcement
 *   Covered by: tests/integration/prototypingSkillV1716Integration.test.ts
 *   (TC-0012-0287 iteration gate)
 *
 * US-0012-0086 — Step 0 execution plan MUST
 *   Covered by: tests/skill/prototypingSkillV1716.test.ts (TC-0012-0289
 *   "Step 0 executionPlan documented"); spec-0017 SKILL.md Step 0.
 *
 * US-0012-0087 — shared screenshot capture script
 *   Superseded by spec-0017 REQ-0002/REQ-0006. Legacy capture-screenshots.js
 *   removed; AI evaluator sub-agents now execute the Playwright CLI command
 *   plan generated by core/prototyping/playwrightCliPlan.ts.
 *
 * US-0012-0088 — 5-step iteration cycle
 *   Superseded by spec-0017 REQ-0005. Cycle evidence now lives under
 *   .qfai/evidence/prototyping/iterations/<n>/ rather than scoringTrace.
 *   Covered by: tests/core/prototyping/evidenceRecord.test.ts +
 *   references/iteration-cycle.md skill documentation.
 *
 * US-0012-0089 — evaluator input preparation protocol
 *   Covered by: tests/skill/prototypingSkillV1716.test.ts (TC-0012-0296
 *   "Evaluator input elements")
 *
 * US-0012-0090 — Visual Quality Structural Checklist
 *   Covered by: tests/skill/prototypingSkillV1716.test.ts (TC-0012-0298
 *   "Visual Quality Structural Checklist 6 categories")
 *
 * US-0012-0091 — Lighthouse MUST for full-harness + web
 *   Superseded by spec-0017 DEC-0017-0007. Lighthouse is no longer a
 *   required completion gate; it remains available as optional evidence.
 *
 * US-0012-0092 — designSystemCompliance Evaluate check
 *   Covered by: tests/integration/prototypingSkillV1716Integration.test.ts
 *   (TC-0012-0301/0302/0303 designSystemCompliance threshold suite)
 *
 * US-0012-0093 — project-side calibration overrides
 *   Covered by: tests/integration/prototypingSkillV1716Integration.test.ts
 *   (TC-0012-0304/0305 applyCalibrationOverrides)
 * -------------------------------------------------------------------------
 *
 * Refs: spec-0012/09_delta.md for the absorbed legacy delta map.
 */

import { access } from "node:fs/promises";
import path from "node:path";

import { describe, expect, it } from "vitest";

const repoRoot = path.resolve(process.cwd(), "..", "..");
const prototypingSkillRoot = path.join(
  repoRoot,
  "packages/qfai/assets/init/.qfai/assistant/skills/qfai-prototyping",
);

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

describe("E2E: spec-0012 v1.7.16 prerequisites", () => {
  it("qfai-prototyping skill directory remains present", async () => {
    expect(await exists(prototypingSkillRoot)).toBe(true);
  });
});
