/**
 * `--capture` evidence-template skeleton emitter.
 *
 * The `qfai prototyping iterate --capture` path writes a skeleton
 * markdown file under the iteration directory containing TODO
 * placeholders for every required `taskFidelity` keyword. The keyword
 * list is sourced from the SSOT at
 * `validators/taskFidelityKeywords.ts` so the validator
 * (`QFAI-CRIT-009`), the shipped doc
 * (`references/evidence-requirements.md`), and the template emitted
 * here never silently diverge.
 *
 * SAFE PLACEMENT INVARIANT (defense-in-depth):
 *
 * The template lands at `.qfai/evidence/prototyping/iter-NN/
 * task-fidelity-template.md` — under the iteration subdirectory.
 * `validateRenderCritique` scans only the DIRECT children of
 * `.qfai/evidence/` (pattern `.qfai/evidence/{prototyping*,
 * critique-*}.md`), so the skeleton does NOT trip CRIT-009 on its
 * own (verified empirically against fast-glob behavior).
 *
 * Even so, the validator has been hardened to reject `TODO` /
 * `FIXME` / `<placeholder>` / empty values for required
 * `taskFidelity` keywords (see `renderCritique.ts#TODO_PLACEHOLDER_RE`),
 * so if an operator copies the placeholder values into a scanned
 * evidence file (`prototyping*.md` or `critique-*.md` at the
 * evidence root), validation rejects the unfilled placeholders with
 * a renderCritique.taskFidelityPlaceholder issue. This keeps the
 * skeleton genuinely advisory: it can only seed the file shape; it
 * cannot satisfy the gate.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  TASK_FIDELITY_REQUIRED_KEYWORDS,
  TASK_FIDELITY_SECTION_NAME,
} from "../validators/taskFidelityKeywords.js";

export const TASK_FIDELITY_TEMPLATE_FILE = "task-fidelity-template.md";

/**
 * Build the template text. The body includes a single
 * `## taskFidelity` section with one TODO bullet per required
 * keyword. Authors fill in the value bytes; the validator
 * (`QFAI-CRIT-009`) then accepts the recorded evidence.
 */
export function buildTaskFidelityTemplate(): string {
  const lines: string[] = [];
  lines.push("# Evidence Capture Template");
  lines.push("");
  lines.push(
    "<!-- Generated by `qfai prototyping iterate --capture`. Fill in each TODO before this evidence is sealed. -->",
  );
  lines.push("");
  lines.push(TASK_FIDELITY_SECTION_NAME);
  lines.push("");
  for (const keyword of TASK_FIDELITY_REQUIRED_KEYWORDS) {
    lines.push(`- ${keyword}: TODO`);
  }
  lines.push("");
  return lines.join("\n");
}

export type WrittenTemplate = {
  readonly path: string;
};

/**
 * Write the template under `iterDir`. Creates the directory tree when
 * absent. Overwrites any prior file (the operator can re-run `--capture`
 * safely; the skeleton is purely a starting point).
 */
export async function writeTaskFidelityTemplate(iterDir: string): Promise<WrittenTemplate> {
  await mkdir(iterDir, { recursive: true });
  const target = path.join(iterDir, TASK_FIDELITY_TEMPLATE_FILE);
  await writeFile(target, buildTaskFidelityTemplate(), "utf-8");
  return { path: target };
}
