/**
 * Cycle-0 `--emit-skeletons` placeholder HTML emission.
 *
 * Authors invoke `qfai prototyping iterate --cycle 0 --emit-skeletons`
 * to seed one placeholder HTML per `screens[].id` resolved from the
 * cycle-0 `frozenSurfaceUnion`. Default mode (`placeholder`) renders a
 * token-driven static placeholder consuming DESIGN.md color / font /
 * radius / shadow tokens — NO per-screen LLM generation call. The
 * `--skeleton-mode` flag selects:
 *
 *   - `placeholder` (default): token-driven static HTML
 *   - `full`: escalates to per-screen LLM generation (caller-supplied;
 *     this module exposes the contract surface only)
 *   - `stub`: minimal `<!doctype html>` marker, no styling
 *
 * The function returns the rendered HTML; the iterate command writes
 * each file under `.qfai/prototypes/iter-00/<screen-id>.html`.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { SAFE_SCREEN_ID_PATTERN } from "../validators/uiEvidenceArtifacts.js";

export type SkeletonMode = "placeholder" | "full" | "stub";

export type SkeletonScreen = {
  readonly id: string;
  /** Optional human-readable title; falls back to capitalised id. */
  readonly title?: string;
};

export type DesignTokensForSkeleton = {
  readonly colors: Readonly<Record<string, string>>;
  readonly fonts: Readonly<Record<string, string>>;
  readonly radius: Readonly<Record<string, string>>;
  readonly shadow: Readonly<Record<string, string>>;
};

export type EmitSkeletonsInput = {
  readonly screens: readonly SkeletonScreen[];
  readonly tokens: DesignTokensForSkeleton;
  readonly mode: SkeletonMode;
};

export type EmittedSkeleton = {
  readonly screenId: string;
  readonly html: string;
};

/**
 * Build the placeholder HTML for one screen. The HTML is purely
 * static — no script tags, no remote fetches, no LLM call.
 */
export function buildSkeletonHtml(
  screen: SkeletonScreen,
  tokens: DesignTokensForSkeleton,
  mode: SkeletonMode,
): string {
  if (mode === "stub") {
    return `<!doctype html>\n<title>${escapeHtml(screen.title ?? screen.id)}</title>\n`;
  }
  if (mode === "full") {
    // The CLI orchestration layer is the one that escalates to a
    // generation call; the renderer here returns the placeholder as
    // a fallback (callers may discard and replace).
    return (
      buildPlaceholderHtml(screen, tokens) +
      "\n<!-- skeleton-mode=full: caller should replace this body via generation -->\n"
    );
  }
  return buildPlaceholderHtml(screen, tokens);
}

function buildPlaceholderHtml(screen: SkeletonScreen, tokens: DesignTokensForSkeleton): string {
  const title = escapeHtml(screen.title ?? capitalise(screen.id));
  const primary = tokens.colors.primary ?? "#2563eb";
  const surface = tokens.colors.surface ?? "#ffffff";
  const text = tokens.colors.text ?? "#111827";
  const fontSans = tokens.fonts.family_sans ?? "system-ui, sans-serif";
  const radiusMd = tokens.radius.md ?? "8px";
  const shadowMd = tokens.shadow.md ?? "0 4px 6px rgba(0,0,0,0.1)";
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    `<title>${title}</title>`,
    "<style>",
    `body { font-family: ${fontSans}; color: ${text}; background: ${surface}; margin: 0; padding: 2rem; }`,
    `.skeleton-card { background: ${surface}; border-radius: ${radiusMd}; box-shadow: ${shadowMd}; padding: 2rem; max-width: 720px; margin: 2rem auto; }`,
    `.skeleton-cta { display: inline-block; background: ${primary}; color: ${surface}; padding: 0.75rem 1.25rem; border-radius: ${radiusMd}; text-decoration: none; }`,
    ".skeleton-label { font-size: 0.875rem; opacity: 0.7; text-transform: uppercase; letter-spacing: 0.05em; }",
    "</style>",
    "</head>",
    "<body>",
    `<main class="skeleton-card">`,
    `<div class="skeleton-label">Placeholder &mdash; ${escapeHtml(screen.id)}</div>`,
    `<h1>${title}</h1>`,
    `<p>This is a token-styled placeholder generated by <code>qfai prototyping iterate --cycle 0 --emit-skeletons</code>. Replace with the actual screen content.</p>`,
    `<a class="skeleton-cta" href="#">Primary CTA</a>`,
    "</main>",
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

/**
 * Render placeholder HTML for every screen in the input. Pure
 * function: returns `EmittedSkeleton[]` without touching disk.
 */
export function buildSkeletonsForUnion(input: EmitSkeletonsInput): readonly EmittedSkeleton[] {
  return input.screens.map((screen) => ({
    screenId: screen.id,
    html: buildSkeletonHtml(screen, input.tokens, input.mode),
  }));
}

/**
 * Allowed screenId character set for the skeleton write path. The UI
 * contract reader accepts arbitrary strings for `screens[].id`, but
 * the writer joins the id directly into a filesystem path — so a
 * malicious or accidentally-formed contract value like
 * `../../outside` could escape `outDir`. Re-use the validator's
 * `SAFE_SCREEN_ID_PATTERN` (single source of truth) so the writer
 * and validator can never drift: a screen id the validator accepts
 * also writes successfully via `--emit-skeletons`, and vice versa.
 *
 * The canonical pattern is `/^[A-Za-z0-9][A-Za-z0-9._-]*$/u`:
 *   - First char: letter or digit (rejects leading `.`, `_`, `-`)
 *   - Subsequent chars: letters, digits, `.`, `_`, `-` only
 *   - Rejects path separators (`/`, `\`, `:`), leading dots
 *     (`.outside`, `..foo`, `../escape`), and any other non-ASCII-
 *     safe input
 */

function isSafeScreenId(id: string): boolean {
  return SAFE_SCREEN_ID_PATTERN.test(id);
}

/**
 * Convenience writer used by the iterate command. Writes each
 * skeleton under `outDir/<id>.html`, creating the directory tree as
 * needed. Returns the absolute paths so the caller can record them.
 *
 * Throws when `screenId` contains anything other than
 * `[A-Za-z0-9_-]` — path-traversal characters (`/`, `\`, `..`, `:`)
 * and any other non-ASCII-safe input must be rejected before the
 * filesystem write so the join cannot escape `outDir`. Callers that
 * want a softer failure mode (warn + skip) can pre-filter the
 * skeleton array.
 */
export async function writeSkeletons(
  outDir: string,
  skeletons: readonly EmittedSkeleton[],
): Promise<readonly string[]> {
  await mkdir(outDir, { recursive: true });
  const written: string[] = [];
  for (const sk of skeletons) {
    if (!isSafeScreenId(sk.screenId)) {
      throw new Error(
        `emitSkeletons: unsafe screenId ${JSON.stringify(sk.screenId)} — ` +
          "must match /^[A-Za-z0-9][A-Za-z0-9._-]*$/ (first char must be a " +
          "letter or digit; subsequent chars must be letters, digits, `.`, " +
          "`_`, or `-`; no path separators). Reject the UI contract entry " +
          "before --emit-skeletons writes any HTML.",
      );
    }
    const target = path.join(outDir, `${sk.screenId}.html`);
    await writeFile(target, sk.html, "utf-8");
    written.push(target);
  }
  return written;
}

function capitalise(value: string): string {
  if (value.length === 0) return value;
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, "&amp;")
    .replace(/</gu, "&lt;")
    .replace(/>/gu, "&gt;")
    .replace(/"/gu, "&quot;")
    .replace(/'/gu, "&#39;");
}
