# OpenAPI contract sample (API-0001)
# - 必須: openapi, info, paths
# - 参照: BR/SC の ID を x-qfai-refs に記載
openapi: 3.0.0
info:
  title: QFAI Sample API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: API-0001
      x-qfai-refs:
        - BR-0001
        - SC-0001
      responses:
        "200":
          description: OK
