# QFAI-CONTRACT-ID: API-0001
# OpenAPI contract sample (API-0001)
# - 必須: QFAI-CONTRACT-ID (1ファイル1ID)
# - 必須: openapi, info, paths
openapi: 3.0.0
info:
  title: QFAI Sample API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: healthCheck
      responses:
        "200":
          description: OK
