# OpenAPI contract sample (API-0001)
# - 必須: openapi, info, paths
# - 重要: operationId に API-0001 のような ID を含める（validate が参照整合に利用）
openapi: 3.0.0
info:
  title: QFAI Sample API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: API-0001
      responses:
        "200":
          description: OK
