/**
 * `qfai-configure` tells the operator where evidence is excluded from Git.
 *
 * It used to say `.qfai/evidence/` "ships with a local `.gitignore`". No file
 * named `.gitignore` exists anywhere under `assets/init/**`, so no project
 * `qfai init` generates has one — the sentence was true only inside qfai's own
 * repository, which carries `.qfai/evidence/.gitignore` as a working-tree file
 * outside the init asset set.
 *
 * The cost is misdirection: an operator who needs the audit trail tracked looks
 * for a per-directory file, does not find it, and never reaches the managed
 * block in the root `.gitignore` that is actually responsible.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import fg from "fast-glob";
import { describe, expect, it } from "vitest";

import { QFAI_GITIGNORE_MARKER, QFAI_GITIGNORE_BLOCK } from "../../src/core/gitignore.js";

// tests/assets/<this file> -> tests -> packages/qfai -> packages -> repo root
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const INIT_ASSETS = path.join(repoRoot, "packages", "qfai", "assets", "init");
const QFAI_TREES = ["packages/qfai/assets/init/.qfai", ".qfai"];
const CONFIGURE_SKILL = "assistant/skills/qfai-configure/SKILL.md";
const VERIFY_SKILL = "assistant/skills/qfai-verify/SKILL.md";

/** Wrap-tolerant containment: the sentence is the rule, its wrap column is not. */
const flat = (s: string): string => s.replace(/\s+/g, " ");

const read = (tree: string, rel: string): Promise<string> =>
  readFile(path.join(repoRoot, tree, rel), "utf-8");

describe("the evidence-ignore claim matches what qfai init actually ships", () => {
  it("ships no .gitignore anywhere in the init assets", async () => {
    // `qfai init` copies `assets/init/**`; a directory-local ignore file cannot
    // appear in a generated project unless it is an asset first.
    const found = await fg(["**/.gitignore"], {
      cwd: INIT_ASSETS,
      dot: true,
      onlyFiles: true,
    });
    expect(found, "an init asset now ships a .gitignore — update the skill text").toEqual([]);
  });

  it("excludes evidence through the root managed block", () => {
    // The mechanism the skill must point at.
    expect(QFAI_GITIGNORE_BLOCK).toContain(QFAI_GITIGNORE_MARKER);
    expect(QFAI_GITIGNORE_BLOCK).toContain(".qfai/evidence/*");
  });

  for (const tree of QFAI_TREES) {
    it(`${tree}: the skill names the root block, not a directory-local file`, async () => {
      const skill = await read(tree, CONFIGURE_SKILL);
      expect(flat(skill)).not.toContain("it ships with a local `.gitignore`");
      expect(flat(skill)).toContain(
        "The mechanism is the QFAI-managed block `npx qfai init` writes into the **project root** `.gitignore`",
      );
      expect(flat(skill)).toContain(
        "A project generated by `npx qfai init` has no per-directory `.qfai/evidence/.gitignore`",
      );
    });

    it(`${tree}: the marker quoted in the skill is the one the code writes`, async () => {
      // Quoting it is what makes the block findable; a stale copy sends the
      // operator hunting for a block that is not there under that name.
      const skill = await read(tree, CONFIGURE_SKILL);
      expect(skill).toContain(QFAI_GITIGNORE_MARKER);
    });

    it(`${tree}: distinguishes local run evidence from committed item evidence`, async () => {
      const configure = await read(tree, CONFIGURE_SKILL);
      const verify = await read(tree, VERIFY_SKILL);

      expect(flat(configure)).toContain(
        "The run-scoped `.qfai/evidence/configure-<run-id>.md` remains local and ignored",
      );
      expect(flat(verify)).toContain(
        "The run-scoped `.qfai/evidence/verify-<spec-id>.md` remains local and ignored",
      );
      for (const skill of [configure, verify]) {
        expect(flat(skill)).toContain(
          "Durable per-item `implement-*.md` and `atdd-*.md` governance records are committed",
        );
        expect(skill).not.toContain("Do NOT commit evidence files");
      }
    });
  }
});
