/**
 * The layer-to-CI-lane mapping document: where it lives, what it must disclaim, and what it
 * must not become.
 *
 * ## Why a sibling file rather than a section
 *
 * The layer-policy loader resolves `catalog/test-layers.md` by exact path and reads nothing
 * else in that directory. So a sibling catalog file is INVISIBLE to it, and a new section
 * inside the catalog would not be — the loader parses that file, and prose there can extract
 * as a token. That asymmetry is the whole reason the mapping is a separate document, and it is
 * what keeps the layer vocabulary from growing by accident.
 *
 * ## What the document must not turn into
 *
 * The layer catalog marks per-level routing as a target state, "not enforced, do not follow
 * yet". A mapping document that reads as activating it would put a reader at odds with the
 * live gate — `QFAI-ATDD-112` scans one directory, and a document telling them to annotate
 * elsewhere would produce work the gate cannot see. So the prose is constrained, not just the
 * vocabulary.
 *
 * ## The mirror direction
 *
 * `packages/qfai/assets/init/.qfai/...` is the authoring side and `.qfai/...` is generated by
 * `pnpm sync:ssot`. A change made only at the root is overwritten by the next sync and then
 * fails the tracked-tree diff, which is why the rows below assert the DIRECTION rather than
 * only the equality: two identical copies say nothing about which one is the source.
 */
// QFAI:SPEC-0017:TC-0017-0076
// QFAI:SPEC-0017:TC-0017-0077
// QFAI:SPEC-0017:TC-0017-0078
// QFAI:SPEC-0017:TC-0017-0079
// QFAI:SPEC-0017:TC-0017-0080
// QFAI:SPEC-0017:TC-0017-0081
// QFAI:SPEC-0017:TC-0017-0082

import { existsSync, readFileSync } from "node:fs";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { defaultConfig } from "../../src/core/config.js";
import { loadLayerPolicy } from "../../src/core/layerPolicy.js";
import { LAYER_TAGS } from "../../src/core/testStrategyTags.js";

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const REPO_ROOT = path.resolve(PACKAGE_ROOT, "..", "..");

/** The catalog directory, on the authoring side and at the mirrored root. */
const ASSET_CATALOG = path.join(PACKAGE_ROOT, "assets", "init", ".qfai", "assistant", "catalog");
const ROOT_CATALOG = path.join(REPO_ROOT, ".qfai", "assistant", "catalog");

/** The mapping document's basename, and the catalog it sits beside. */
const MAPPING = "test-layers-ci-lanes.md";
const CATALOG = "test-layers.md";

/** The sync script that makes the root copy a mirror. */
const SYNC_SCRIPT = path.join(REPO_ROOT, "scripts", "sync-init-to-root.mjs");

const read = (dir: string, file: string): string => readFileSync(path.join(dir, file), "utf-8");

describe("TC-0017-0076 (TDD-0076): the mapping file exists in both trees and is cross-linked", () => {
  it("exists on both sides and links to the catalog, which links back", () => {
    // CLAIM 1 — both copies. The asset copy is the one a reader edits; the root copy is what
    // this repository's own tooling reads, and an adopter receives the asset copy through
    // `qfai init`. A document present on only one side is invisible to half its audience.
    for (const [label, dir] of [
      ["the asset tree", ASSET_CATALOG],
      ["the mirrored root", ROOT_CATALOG],
    ] as const) {
      expect
        .soft(existsSync(path.join(dir, MAPPING)), `${MAPPING} must exist in ${label}`)
        .toBe(true);
    }
    if (!existsSync(path.join(ASSET_CATALOG, MAPPING))) return;

    // CLAIM 2 — the mapping links to the catalog, and the catalog links back. One direction
    // is not enough: a document nothing points at is a document nobody finds, and a pointer
    // to a document that does not acknowledge it is how the two drift apart.
    expect
      .soft(read(ASSET_CATALOG, MAPPING), "the mapping must link to the layer catalog")
      .toContain(CATALOG);
    expect
      .soft(read(ASSET_CATALOG, CATALOG), "the layer catalog must link back to the mapping")
      .toContain(MAPPING);
  });
});

describe("TC-0017-0077 (TDD-0077): the mapping file header disclaims the layer-policy loader", () => {
  it("says in its header that the loader does not read it", () => {
    const text = read(ASSET_CATALOG, MAPPING);

    // In the HEADER, not somewhere in the body: a reader who stops after the first screen is
    // exactly the reader who would otherwise take a catalog-directory file for enforced
    // vocabulary. The first six hundred characters are the header for this purpose.
    const header = text.slice(0, 600);
    expect
      .soft(header, "the header must state that the layer-policy loader does not read this file")
      .toMatch(/does not read|not read by|reads only/i);
    expect
      .soft(header, "and it must name the loader or the file the loader does read")
      .toMatch(/layer-policy|layer policy|test-layers\.md/i);
  });
});

describe("TC-0017-0078 (TDD-0078): the mapping file does not read as activating routing", () => {
  it("repeats the not-enforced status wherever it names per-level routing, and directs no annotation", () => {
    const text = read(ASSET_CATALOG, MAPPING);

    // CLAIM 1 — per-level routing, if mentioned, is marked unenforced. The layer catalog says
    // "not enforced, do not follow yet"; a sibling that mentions the same idea without that
    // qualifier is the document a reader will act on.
    if (/per-level/i.test(text)) {
      expect
        .soft(text, "a mention of per-level routing must carry its not-enforced status")
        .toMatch(/not enforced/i);
    }

    // CLAIM 2 — and the document tells nobody to annotate outside the directory the live gate
    // scans. `QFAI-ATDD-112` reads `tests/integration/**` for `TC-*` annotations, so an
    // instruction to put them elsewhere produces work the gate cannot see — which is worse
    // than no instruction, because it looks like coverage.
    // Case-INSENSITIVE, and the oracle is why: a planted "Place each annotation ..." reddened
    // nothing, because a sentence-initial capital does not match a lowercase-only alternation.
    // Directives are usually written at the start of a sentence, so the case-sensitive version
    // would have missed the shape it exists to catch.
    const directives = text
      .split(/\r?\n/)
      .filter((line) => /\bmust\b|\bplace\b|\bput\b/i.test(line))
      .filter((line) => /annotat/i.test(line));
    expect
      .soft(directives, "the mapping must not direct where TC annotations are placed")
      .toEqual([]);
  });
});

describe("TC-0017-0079 (TDD-0079): the vocabulary warning count is unchanged after it lands", () => {
  it("introduces no layer code the catalog does not already carry, and is not the file the loader reads", async () => {
    const mapping = read(ASSET_CATALOG, MAPPING);
    const catalog = read(ASSET_CATALOG, CATALOG);

    // CLAIM 1 — every layer code the mapping names appears in the catalog. This is the clause
    // that keeps the vocabulary from growing: the loader compares the catalog's declared set
    // against the built-in one and reports a drift, so a new code introduced anywhere a reader
    // treats as authoritative is a code somebody will eventually add to the catalog.
    const codes = [...new Set([...mapping.matchAll(/\bL[1-9]\b/g)].map((m) => m[0]))].sort();
    const unknown = codes.filter((code) => !catalog.includes(`| ${code} `));
    expect
      .soft(unknown, "every layer code the mapping names must already exist in the catalog")
      .toEqual([]);

    // CLAIM 2 — and this file is not the one the loader resolves. The invisibility is the
    // mechanism, so it is asserted by RUNNING the loader rather than by reading its source.
    //
    // Three attempts at this claim, and the first two both read text:
    //
    //   round 4:  expect(MAPPING).not.toBe(CATALOG)          — two literals defined 20 lines apart
    //   round 5:  the loader's source must not contain MAPPING — the catalog's name occurs SIX
    //             times there, so renaming the resolved file left it green
    //   round 6:  path.join(...) argument lists only          — `[^)]*` stops at the first `)`, so
    //             `path.join(path.dirname(x), "catalog", MAPPING)` captured `path.dirname(x` and
    //             the filename never entered the list; `path.resolve` was not matched at all
    //
    // Each was a syntactic proxy that the natural way of writing the change walks past. The
    // property itself is behavioural: put the mapping document beside the catalog, give it a layer
    // token the catalog does not carry, and the loader must not see it. That is immune to
    // `path.join` versus `path.resolve` versus a constant, and it has no false positive on a
    // behaviour-preserving refactor. Round 6 finding F-1.
    const root = await mkdtemp(path.join(tmpdir(), "qfai-mapping-invisibility-"));
    try {
      const assistantRoot = path.join(root, ".qfai", "assistant");
      await mkdir(path.join(assistantRoot, "skills"), { recursive: true });
      await mkdir(path.join(assistantRoot, "catalog"), { recursive: true });
      // The real catalog, so the tags resolve from the policy file rather than the built-in set.
      await writeFile(
        path.join(assistantRoot, "catalog", CATALOG),
        read(ASSET_CATALOG, CATALOG),
        "utf-8",
      );
      // The real mapping document, plus a token the catalog does not carry. If the loader ever
      // reads this file, `layer-quantum` enters its tag set and both claims below fail.
      await writeFile(
        path.join(assistantRoot, "catalog", MAPPING),
        `${read(ASSET_CATALOG, MAPPING)}\n\n### LQ Quantum\n\nTag: \`layer-quantum\`\n`,
        "utf-8",
      );

      const policy = await loadLayerPolicy(root, defaultConfig);

      expect
        .soft(policy.source, "the loader must resolve the catalog, not fall back to the built-ins")
        .toBe("policy-file");
      expect
        .soft(
          [...policy.tags].filter((tag) => tag === "layer-quantum"),
          `the loader must not read ${MAPPING}; its invisibility to the policy reader is the mechanism this document relies on`,
        )
        .toEqual([]);
      expect
        .soft(
          policy.issues.filter((entry) => entry.code === "QFAI-SPACK-091"),
          "and reading it must not introduce policy-versus-built-in drift",
        )
        .toEqual([]);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});

describe("TC-0017-0080 (TDD-0080): the built-in layer token set is unmodified", () => {
  it("holds exactly the five tokens, imported from the source rather than restated", () => {
    // Imported from `src`, not copied: the claim is that the SET did not change, and a
    // test-local copy would be satisfied by editing both. The five literals are the expected
    // value and they are the only part written twice, which is what makes the comparison real.
    expect
      .soft([...LAYER_TAGS].sort(), "the built-in layer token set must not grow or shrink")
      .toEqual(["layer-api", "layer-component", "layer-e2e", "layer-integration", "layer-unit"]);
  });
});

describe("TC-0017-0081 (TDD-0081): authoring in the asset tree passes both mirror gates", () => {
  it("keeps the two copies byte-identical", () => {
    if (!existsSync(path.join(ROOT_CATALOG, MAPPING))) {
      expect.soft(false, `${MAPPING} must exist at the mirrored root`).toBe(true);
      return;
    }
    // Byte-identical, not merely both present. `pnpm sync:ssot` copies rather than
    // transforming, and `ci:gate` follows it with `git diff --exit-code .qfai/` — so any
    // difference between the two is a failure waiting for the next gate run rather than a
    // variant that works.
    expect
      .soft(read(ROOT_CATALOG, MAPPING), "the mirrored copy must be identical to the authored one")
      .toBe(read(ASSET_CATALOG, MAPPING));
  });
});

describe("TC-0017-0082 (TDD-0082): a root-only edit is reverted and fails the tracked-tree diff", () => {
  it("mirrors from the asset tree to the root, and offers a check mode that detects a divergence", () => {
    const script = readFileSync(SYNC_SCRIPT, "utf-8");

    // CLAIM 1 — the DIRECTION. Two identical copies say nothing about which is the source, so
    // the row reads the script: the asset tree is resolved as the source and the root as the
    // target. That is what makes a root-only edit temporary rather than an alternative.
    const sourceLine = script.split(/\r?\n/).find((line) => /const\s+INIT_QFAI\s*=/.test(line));
    const targetLine = script.split(/\r?\n/).find((line) => /const\s+TARGET_QFAI\s*=/.test(line));
    expect.soft(sourceLine ?? "", "the source must be the asset tree").toContain("assets");
    expect
      .soft(targetLine ?? "", "the target must be the repository root's .qfai")
      .toContain('".qfai"');

    // CLAIM 2 — and a check mode exists, so the divergence is detectable without writing. The
    // aggregate runs the sync and then diffs the tracked tree; the check mode is what lets a
    // reviewer see the same thing without mutating their working copy.
    expect.soft(script, "the sync script must offer a check mode").toMatch(/--check/);
  });
});
