import { readFile } from "node:fs/promises";
import path from "node:path";

import fg from "fast-glob";
import { describe, expect, it } from "vitest";

const repoRoot = path.resolve(process.cwd(), "..", "..");

/** Shipped skill bodies — the set `communication.md` names by glob. */
const SHIPPED_SKILLS_GLOB = "packages/qfai/assets/init/.qfai/assistant/skill/*/SKILL.md";

/** Root mirror of the shipped surface, regenerated by `pnpm sync:ssot`. */
const ROOT_SKILLS_GLOB = ".qfai/assistant/skill/*/SKILL.md";

const COMMUNICATION_PATHS = [
  "packages/qfai/assets/init/.qfai/assistant/rule/communication.md",
  ".qfai/assistant/rule/communication.md",
];

const BASELINE_PATHS = [
  "packages/qfai/assets/init/.qfai/assistant/rule/shared-skill-operating-baseline.md",
  ".qfai/assistant/rule/shared-skill-operating-baseline.md",
];

const HEADING = "## User Questions (AskUserQuestion Protocol)";

/**
 * The anchor every skill body cites instead of restating the four MUSTs. A
 * pointer that stops resolving turns the inherited protocol back into prose.
 */
const BASELINE_ANCHOR =
  "shared-skill-operating-baseline.md#user-questions-askuserquestion-protocol";

async function collectSkillBodies(): Promise<string[]> {
  const shipped = await fg(SHIPPED_SKILLS_GLOB, { cwd: repoRoot, absolute: false });
  const mirrored = await fg(ROOT_SKILLS_GLOB, { cwd: repoRoot, absolute: false });
  return [...shipped, ...mirrored];
}

describe("every shipped SKILL.md carries the AskUserQuestion protocol section", () => {
  it("the communication rule still states the requirement", async () => {
    for (const relativePath of COMMUNICATION_PATHS) {
      const absolute = path.join(repoRoot, relativePath);
      const content = await readFile(absolute, "utf-8");
      expect(content).toContain("All SKILL.md files MUST include a");
      expect(content).toContain("`## User Questions (AskUserQuestion Protocol)` section");
    }
  });

  it("no shipped skill body is missing the heading", async () => {
    const files = await collectSkillBodies();
    expect(files.length).toBeGreaterThan(0);

    const missing: string[] = [];
    for (const relativePath of files) {
      const content = await readFile(path.join(repoRoot, relativePath), "utf-8");
      if (!content.includes(HEADING)) {
        missing.push(relativePath);
      }
    }

    expect(
      missing,
      "communication.md MUSTs this section in every SKILL.md under the shipped skills glob",
    ).toEqual([]);
  });

  it("each section resolves to the shared baseline that carries the MUSTs", async () => {
    const files = await collectSkillBodies();
    const dangling: string[] = [];
    for (const relativePath of files) {
      const content = await readFile(path.join(repoRoot, relativePath), "utf-8");
      if (content.includes(HEADING) && !content.includes(BASELINE_ANCHOR)) {
        dangling.push(relativePath);
      }
    }
    expect(dangling).toEqual([]);
  });

  it("the shared baseline carries the four MUSTs the skills inherit", async () => {
    for (const relativePath of BASELINE_PATHS) {
      const absolute = path.join(repoRoot, relativePath);
      const content = await readFile(absolute, "utf-8");
      expect(content).toContain(HEADING);
      expect(content).toContain("use AskUserQuestion if the tool is available");
      expect(content).toContain("prefer structured choices over free-text input");
      expect(content).toContain("explicit numbered choices");
      expect(content).toContain("State why AskUserQuestion was unavailable.");
      // The fourth MUST (`communication.md` rule 4 / Constitution Article X.4):
      // without it a skill body that says "ask through the protocol" would
      // stall a non-interactive `--auto` run waiting on input.
      expect(content).toContain("When `--auto` is active, ask nothing");
      expect(content).toContain(
        "Proceed with explicit assumptions and record them in the outputs.",
      );
    }
  });

  it("covers the skills that shipped without the section", async () => {
    const files = await collectSkillBodies();
    for (const required of [
      "packages/qfai/assets/init/.qfai/assistant/skill/qfai-atdd/SKILL.md",
      "packages/qfai/assets/init/.qfai/assistant/skill/qfai-implement/SKILL.md",
      "packages/qfai/assets/init/.qfai/assistant/skill/qfai-discussion/SKILL.md",
      "packages/qfai/assets/init/.qfai/assistant/skill/qfai-prototyping/SKILL.md",
    ]) {
      expect(files).toContain(required);
    }
  });
});
