import { parseAgentFrontmatter } from "./agentFrontmatter.js";

/**
 * Codex reads its sub-agent profiles from `.codex/agents/<name>.toml`, one TOML
 * document per agent, with the whole agent body carried in a single
 * `developer_instructions` string.
 *
 * The other two integrations (`.claude/agents/<name>.md`,
 * `.github/agents/<name>.agent.md`) are symlinks into
 * `.qfai/assistant/agent/`, so a correction to a canonical agent document
 * reaches them the moment it lands. TOML cannot be a symlink to markdown: the
 * body has to be escaped into a string field. So this wrapper is a *generated*
 * file, and it goes stale unless something regenerates it — which is why
 * `qfai init --force` rewrites it alongside `assistant/agents/**`.
 */
export const CODEX_AGENT_WRAPPER_DIR = ".codex/agents";

/** Filename suffix under {@link CODEX_AGENT_WRAPPER_DIR}. */
export const CODEX_AGENT_WRAPPER_SUFFIX = ".toml";

export type CodexAgentKind = "worker" | "reviewer";

/**
 * Reviewers run without write access; workers leave `sandbox_mode` unset so
 * Codex applies its own default. The split is declared once, in
 * the card's `kind` frontmatter field.
 */
const REVIEWER_SANDBOX_MODE = "read-only";

/** Where a canonical agent body starts — everything above it is the H1 title. */
const BODY_START_MARKER = "## Mission";

/**
 * The heading, anchored to a whole line.
 *
 * A substring search finds `## Mission` wherever it appears, frontmatter
 * included — `description: "Use the ## Mission section"` is valid YAML and
 * would move the body start above the closing `---`, handing Codex a
 * `developer_instructions` that opens with the rest of the frontmatter and the
 * H1. The document still parses as TOML, so nothing downstream catches it.
 * `\b` rather than `$` so a heading that carries a subtitle
 * (`## Mission and scope`) still starts the body, as the substring search did.
 */
const BODY_START_HEADING_RE = /^## Mission\b/m;

/** Matches {@link parseAgentFrontmatter}'s block, on LF-normalised input. */
const FRONTMATTER_BLOCK_RE = /^---\n[\s\S]*?\n---(?:\n|$)/;

/**
 * Offset of the first character after the frontmatter block, or 0 when the
 * document has none.
 */
function bodySearchStart(normalized: string): number {
  return FRONTMATTER_BLOCK_RE.exec(normalized)?.[0].length ?? 0;
}

const TOML_ESCAPES = new Map<string, string>([
  ["\\", "\\\\"],
  ['"', '\\"'],
  ["\n", "\\n"],
  ["\r", "\\r"],
  ["\t", "\\t"],
  ["\b", "\\b"],
  ["\f", "\\f"],
]);

const DELETE_CODE_POINT = 0x7f;
const FIRST_PRINTABLE_CODE_POINT = 0x20;

/**
 * Renders a TOML basic string, quotes included.
 *
 * TOML forbids raw control characters inside a basic string, so anything below
 * U+0020 (plus U+007F) that has no short escape is emitted as `\uXXXX`. Agent
 * bodies are markdown and routinely contain `"` and `\` — an unescaped one
 * would truncate `developer_instructions` at that character and hand Codex a
 * silently half-loaded agent.
 */
export function escapeTomlBasicString(value: string): string {
  let escaped = "";
  for (const character of value) {
    const shortEscape = TOML_ESCAPES.get(character);
    if (shortEscape !== undefined) {
      escaped += shortEscape;
      continue;
    }
    const codePoint = character.codePointAt(0) ?? 0;
    if (codePoint < FIRST_PRINTABLE_CODE_POINT || codePoint === DELETE_CODE_POINT) {
      escaped += `\\u${codePoint.toString(16).padStart(4, "0")}`;
      continue;
    }
    escaped += character;
  }
  return `"${escaped}"`;
}

export type CodexAgentTomlInput = {
  name: string;
  description: string;
  /** The canonical agent body, from `## Mission` onward. */
  body: string;
  kind: CodexAgentKind;
};

/**
 * First line of every generated profile, and the only thing that licenses
 * `--force` to delete one.
 *
 * The shape of the document cannot carry that licence on its own: a project's
 * own minimal worker profile is `name` / `description` /
 * `developer_instructions`, three single-line basic strings, which is exactly
 * what this generator emits — so a shape test would have handed `--force` the
 * right to delete a hand-written agent the roster happens not to name. A
 * comment nobody types by accident is a statement about provenance rather than
 * about form.
 */
export const CODEX_AGENT_GENERATED_MARKER =
  "# Generated by `qfai init` from .qfai/assistant/agent/ — edits are overwritten.";
const LEGACY_CODEX_AGENT_GENERATED_MARKER =
  "# Generated by `npx qfai init` from .qfai/assistant/agents/ — edits are overwritten.";

/** Emits the marked, four-field TOML document, LF-terminated. */
export function buildCodexAgentToml(input: CodexAgentTomlInput): string {
  const lines = [
    CODEX_AGENT_GENERATED_MARKER,
    `name = ${escapeTomlBasicString(input.name)}`,
    `description = ${escapeTomlBasicString(input.description)}`,
  ];
  if (input.kind === "reviewer") {
    lines.push(`sandbox_mode = ${escapeTomlBasicString(REVIEWER_SANDBOX_MODE)}`);
  }
  lines.push(`developer_instructions = ${escapeTomlBasicString(input.body)}`);
  return `${lines.join("\n")}\n`;
}

/** The key order {@link buildCodexAgentToml} emits, per kind. */
const GENERATED_KEY_ORDER: Record<CodexAgentKind, readonly string[]> = {
  worker: ["name", "description", "developer_instructions"],
  reviewer: ["name", "description", "sandbox_mode", "developer_instructions"],
};

/**
 * True when `content` is this generator's own output for `agentName`: the
 * {@link CODEX_AGENT_GENERATED_MARKER} line, then one `key = "…"` line per
 * field, in order, nothing else.
 *
 * `.codex/agents/` is not a directory qfai owns end to end — a project may keep
 * its own Codex profiles there — so pruning by filename alone would delete
 * somebody's hand-written agent the first time they ran `--force`. Neither is
 * the shape enough: a minimal hand-written worker profile is the same three
 * single-line basic strings this generator emits. The marker is what a project
 * does not write by accident, so it, and not the shape, is the licence to
 * delete.
 */
export function isGeneratedCodexAgentToml(content: string, agentName: string): boolean {
  const lines = content.replace(/\r\n/g, "\n").replace(/\n+$/, "").split("\n");
  if (
    lines[0] !== CODEX_AGENT_GENERATED_MARKER &&
    lines[0] !== LEGACY_CODEX_AGENT_GENERATED_MARKER
  ) {
    return false;
  }
  const keyLines = lines.slice(1);
  const expected =
    keyLines.length === GENERATED_KEY_ORDER.reviewer.length
      ? GENERATED_KEY_ORDER.reviewer
      : GENERATED_KEY_ORDER.worker;
  if (keyLines.length !== expected.length) {
    return false;
  }
  if (keyLines[0] !== `name = ${escapeTomlBasicString(agentName)}`) {
    return false;
  }
  return keyLines.every((line, index) => {
    const key = expected[index];
    return key !== undefined && line.startsWith(`${key} = "`) && line.endsWith('"');
  });
}

export type CodexAgentTomlResult = { ok: true; toml: string } | { ok: false; error: string };

/** The next heading at `## Mission`'s level or above — where its section ends. */
const NEXT_SECTION_HEADING_RE = /^#{1,2} /m;

/**
 * The `## Mission` section's own content: everything after the heading line, up
 * to the next heading at that level or above.
 *
 * The profile still carries the whole document from the heading onward — Codex
 * wants the entire agent — but a document that opens its Mission and says
 * nothing under it is not an agent definition, and the emptiness has to be
 * measured on the section rather than on the slice that starts with the heading
 * text itself.
 */
function missionSectionContent(normalized: string, headingOffset: number): string {
  const lineEnd = normalized.indexOf("\n", headingOffset);
  if (lineEnd < 0) {
    return "";
  }
  const afterHeading = normalized.slice(lineEnd + 1);
  const nextHeading = NEXT_SECTION_HEADING_RE.exec(afterHeading);
  return nextHeading === null ? afterHeading : afterHeading.slice(0, nextHeading.index);
}

/**
 * Turns one canonical `.qfai/assistant/agent/<name>.md` document into its
 * Codex profile. `name` / `description` come from the shared frontmatter, so
 * the three integrations cannot disagree about either.
 *
 * `agentName` is the name the file is filed under — the card ID and the
 * `<name>.toml` stem. A document whose frontmatter disagrees with it is
 * refused rather than rendered: the profile would be written to `foo.toml`
 * carrying `name = "bar"`, which Codex reads as a different agent and which
 * {@link isGeneratedCodexAgentToml} no longer recognises as this generator's,
 * so the stale file could never be pruned either.
 */
export function renderCodexAgentToml(
  markdown: string,
  kind: CodexAgentKind,
  agentName: string,
): CodexAgentTomlResult {
  const frontmatter = parseAgentFrontmatter(markdown);
  if (!frontmatter.ok) {
    return { ok: false, error: frontmatter.error };
  }
  if (frontmatter.frontmatter.name !== agentName) {
    return {
      ok: false,
      error: `frontmatter.name (${frontmatter.frontmatter.name}) がファイル名 (${agentName}) と一致しません`,
    };
  }
  if (frontmatter.frontmatter.kind !== kind) {
    return { ok: false, error: `frontmatter.kind does not match ${kind}` };
  }

  const normalized = markdown.replace(/\r\n/g, "\n");
  const searchStart = bodySearchStart(normalized);
  const heading = BODY_START_HEADING_RE.exec(normalized.slice(searchStart));
  if (heading === null) {
    return { ok: false, error: `missing \`${BODY_START_MARKER}\` section` };
  }
  const headingOffset = searchStart + heading.index;
  if (missionSectionContent(normalized, headingOffset).trim().length === 0) {
    return { ok: false, error: `\`${BODY_START_MARKER}\` section is empty` };
  }
  const body = normalized.slice(headingOffset).trim();

  return {
    ok: true,
    toml: buildCodexAgentToml({
      name: frontmatter.frontmatter.name,
      description: frontmatter.frontmatter.description,
      body,
      kind,
    }),
  };
}

/** Classify a card only when its entire frontmatter is valid and its name matches the file. */
export function parseAgentCardKind(markdown: string, expectedName: string): CodexAgentKind | null {
  const parsed = parseAgentFrontmatter(markdown);
  return parsed.ok && parsed.frontmatter.name === expectedName ? parsed.frontmatter.kind : null;
}
