/**
 * Shared constants for QFAI-managed .gitignore block.
 * Used by both `qfai init` (writer) and validators (reader).
 */

export const QFAI_GITIGNORE_MARKER = "# ── QFAI managed (generated by qfai init) ──";

/**
 * Suffix of every staging directory the atomic `.qfai/state.json` write
 * creates (`core/state.ts`, `<document>.<pid>.<random>.qfai-state.tmp/`).
 * `core/state.ts` builds the names from this constant, so the ignore pattern
 * below and the real names cannot drift.
 */
export const QFAI_STATE_SCRATCH_SUFFIX = ".qfai-state.tmp";

/**
 * The staging directories that write leaves behind when a run is killed
 * between filling the scratch and renaming it over the document.
 *
 * `rename` needs both names on one filesystem, so the staging directory has to
 * sit beside the document it replaces; the next state write sweeps it, but a
 * checkout whose next command never writes state keeps it — and an untracked,
 * half-written state document beside an ignored one is exactly what
 * `git add .` commits by accident. Ignoring the shape is what makes the
 * leftover harmless rather than merely short-lived.
 *
 * Deliberately NOT anchored to `.qfai/`: a `state.json` that is a live symlink
 * is written through to its target (`core/state.ts#prepareWriteTarget`), so the
 * staging directory is created next to THAT file, which an anchored pattern
 * would never cover. Matching on the suffix alone covers every location the
 * write can resolve to inside the repository.
 *
 * `tests/unit/core/stateWritePermissions.test.ts` pins the real staging name
 * against this pattern, for the plain and the symlinked document alike.
 */
export const QFAI_STATE_SCRATCH_IGNORE = `*${QFAI_STATE_SCRATCH_SUFFIX}`;

/**
 * Gitignore entries qfai init writes alongside the marker.
 *
 * Recommended, not required: QFAI-REVIEW-008 reports a missing one at
 * info. .qfai/evidence/**, .qfai/review/** and .qfai/discussion/**
 * hold governance records a project may legitimately want tracked, and
 * failing validation for tracking your own audit trail is the wrong answer.
 * Named for that semantics — the old _REQUIRED_ read as a hard gate this
 * has not been since the severity moved to info.
 */
export const QFAI_GITIGNORE_RECOMMENDED_ENTRIES: readonly string[] = [
  ".qfai/report/*",
  ".qfai/evidence/*",
  ".qfai/discussion/*",
  ".qfai/review/*",
  // Per-runtime state. Written by `qfai discussion use`,
  // `qfai atdd scaffold` (escalation counters), and any future
  // single-file state holder. The file header explicitly states
  // "NOT committed configuration"; without this entry every normal
  // CLI run leaves an untracked `.qfai/state.json` in the consumer
  // repo and makes it trivial to accidentally `git add .` and
  // commit local session pointers / counters.
  ".qfai/state.json",
  // The staging directories that file's atomic write uses; see
  // QFAI_STATE_SCRATCH_IGNORE.
  QFAI_STATE_SCRATCH_IGNORE,
] as const;

/**
 * Governance records that must stay in version control: Change Requests
 * carrying user approval, and durable decision records. `qfai init` writes
 * these negations after the ignore lines so the later pattern wins.
 *
 * They are deliberately NOT in `QFAI_GITIGNORE_RECOMMENDED_ENTRIES`: an existing
 * project whose `.gitignore` predates them must not start failing validation.
 */
export const QFAI_GITIGNORE_GOVERNANCE_NEGATIONS: readonly string[] = [
  // Parent re-inclusions. Git cannot re-include a path whose PARENT directory
  // is excluded, so a leaf negation alone is inert against a broad pre-existing
  // rule an adopting project already had:
  //   `.qfai/`          excludes `.qfai` itself -> `!.qfai/` is required
  //   `.qfai/*`         excludes `.qfai/evidence` -> `!.qfai/evidence/` too
  //   `.qfai/evidence/` excludes the directory   -> `!.qfai/evidence/` too
  // Measured with `git check-ignore -v .qfai/evidence/decisions/a.json`: without
  // these two lines all three shapes still report the broad rule as the winner.
  // Neither line widens the managed block. `!.qfai/` and `!.qfai/evidence/`
  // match the directories only, so the `.qfai/<subtree>/*` ignores above still
  // win for every generated file (evidence/prototyping, report, discussion,
  // review); the only paths they re-expose are the ones QFAI already expects to
  // be tracked (`specs/`, `contracts/`, `assistant/`).
  "!.qfai/",
  "!.qfai/evidence/",
  "!.qfai/decisions/",
  "!.qfai/decisions/**",
  // The real durable-decision write target: `writeDecisionRecord` persists
  // `.qfai/evidence/decisions/<ISO8601-stamp>.json` (see
  // `core/decisionRecord.ts#DECISIONS_REL`). Git never descends into an
  // ignored directory, so `.qfai/evidence/*` must be undone for the directory
  // itself before its contents can be re-included.
  "!.qfai/evidence/decisions/",
  "!.qfai/evidence/decisions/**",
  "!.qfai/evidence/change-request-*.md",
  "!.qfai/evidence/decision-*.md",
  // The Coverage Depth Matrix and the justification behind each `❌` cell.
  // `/qfai-atdd` makes "no unjustified ❌ cells" both a Definition-of-Done
  // condition and a Not-done criterion, and `qa-gatekeeper` REVISEs a missing
  // matrix — so the judgement that discharges those gates is a governance
  // record, not a regenerable log. Re-running the stage recomputes the cells;
  // it does not recompute *why* an uncoverable obligation was accepted. Left
  // inside the ignored stage-evidence file, that reasoning never reaches a
  // commit and "unjustified" becomes unfalsifiable for every later reader.
  "!.qfai/evidence/coverage-depth-*.md",
  // The migration record naming the review packs that predate the strict
  // `revision` form. Every other file under `.qfai/review/` is a regenerable
  // record of one round, but this one is written once, from the history, and
  // read by `QFAI-REVIEW-007` to decide whether a pack's own `legacy` claim is
  // believed. Left untracked, the pack a claim excuses could add itself to it,
  // which is the self-declaration the corroboration exists to replace.
  "!.qfai/review/",
  "!.qfai/review/.legacy-packs",
] as const;

/**
 * Retired lines that were **renamed** rather than dropped, mapped to their
 * successor.
 *
 * Migration strips every entry of {@link QFAI_GITIGNORE_LEGACY_LINES} and does
 * not re-add recommended ignores a project removed on purpose. A renamed line
 * is the one case where that would take away something the project never gave
 * up: dropping the old discussion ignore without adding the one that replaced
 * it leaves the project with no discussion ignore at all.
 */
export const RETIRED_LINE_SUCCESSORS: Readonly<Record<string, string>> = {
  ".qfai/discussion/discussion-*/": ".qfai/discussion/*",
};

/** Lines removed from the managed block in previous versions; stripped during migration. */
export const QFAI_GITIGNORE_LEGACY_LINES: readonly string[] = [
  "!.qfai/report/README.md",
  "!.qfai/evidence/README.md",
  "!.qfai/discussion/README.md",
  "!.qfai/review/README.md",
  ".qfai/discussion/discussion-*/",
  "!.qfai/review/review-*/",
  "!.qfai/review/review-*/**",
] as const;

export const QFAI_GITIGNORE_BLOCK = [
  QFAI_GITIGNORE_MARKER,
  ".qfai/report/*",
  ".qfai/evidence/*",
  ".qfai/discussion/*",
  ".qfai/review/*",
  ".qfai/state.json",
  QFAI_STATE_SCRATCH_IGNORE,
  // Negations last: git applies the last matching pattern, so these re-include
  // the governance records the ignores above would otherwise swallow.
  ...QFAI_GITIGNORE_GOVERNANCE_NEGATIONS,
  "",
].join("\n");

/**
 * True when `pattern` — one ignore line — could match `samplePath`.
 *
 * A presence check is not enough for a negation: git applies the **last**
 * matching pattern, so a negation is effective only when no ignore line below
 * it matches the same path. Deciding that needs real gitignore glob semantics,
 * not a prefix comparison — a prefix test cannot see that `*.md` or
 * `**` + `/*.md`, placed after `!.qfai/evidence/coverage-depth-*.md`,
 * re-ignores exactly what the negation re-included.
 *
 * Implemented rules, the ones a real `.gitignore` uses:
 *
 * - a leading `/`, or any `/` before the final character, anchors the pattern
 *   to the file's directory; otherwise it matches at any depth;
 * - a trailing `/` names a directory, and a directory pattern also covers
 *   everything beneath it;
 * - the double-star form crosses `/`, a single `*` does not, and `?` matches
 *   one non-`/` character.
 *
 * Blank lines, comments and negations are not ignore lines and never match.
 */
export function gitignorePatternMatches(pattern: string, samplePath: string): boolean {
  const trimmed = pattern.trim();
  if (trimmed.length === 0 || trimmed.startsWith("#") || trimmed.startsWith("!")) {
    return false;
  }

  const withoutTrailingSlash = trimmed.endsWith("/") ? trimmed.slice(0, -1) : trimmed;
  // Per gitignore(5): a `/` anywhere but the end anchors the pattern.
  const anchored = withoutTrailingSlash.includes("/");
  const body = withoutTrailingSlash.replace(/^\//, "");
  if (body.length === 0) {
    return false;
  }

  const DOUBLE_STAR_SLASH = " ds ";
  const DOUBLE_STAR = " d ";
  const source = body
    .replace(/[.+^${}()|[\]\\]/g, (char) => `\\${char}`)
    // Order matters: the two double-star forms are parked before the
    // single-`*` rule can eat them, then restored.
    .replace(/\*\*\//g, DOUBLE_STAR_SLASH)
    .replace(/\*\*/g, DOUBLE_STAR)
    .replace(/\*/g, "[^/]*")
    .replace(/\?/g, "[^/]")
    .split(DOUBLE_STAR_SLASH)
    .join("(?:.*/)?")
    .split(DOUBLE_STAR)
    .join(".*");

  // The trailing group is what makes a directory pattern cover its contents.
  const prefix = anchored ? "^" : "^(?:.*/)?";
  return new RegExp(`${prefix}${source}(?:/.*)?$`).test(samplePath.replace(/^\//, ""));
}

/**
 * A concrete path the negation re-includes, for feeding
 * {@link gitignorePatternMatches}.
 *
 * A negation is itself a glob, and glob-vs-glob overlap has no cheap exact
 * answer. A representative instance is enough and errs the safe way: a false
 * "conflict" only re-appends a negation that was already last, which is where
 * it belongs anyway.
 */
export function negationSamplePath(negation: string): string {
  const body = negation.replace(/^!/, "");
  const withContents = body.endsWith("/") ? `${body}sample` : body;
  return withContents.replace(/\*\*/g, "sample/leaf").replace(/\*/g, "sample");
}

/**
 * True when every one of `negations` is still the last word on the paths it
 * re-includes.
 *
 * `lines` is the whole file, not one block: a project that appended
 * `.qfai/evidence/*.md` **after** the managed block wins under git's
 * last-match rule, and a block-scoped check calls the negation effective while
 * `git check-ignore -v` names the project's line.
 */
export function negationsOutrankLaterIgnores(
  lines: readonly string[],
  negations: readonly string[],
): boolean {
  for (const negation of negations) {
    const at = lines.lastIndexOf(negation);
    if (at === -1) {
      return false;
    }
    const sample = negationSamplePath(negation);
    for (let index = at + 1; index < lines.length; index += 1) {
      if (gitignorePatternMatches(lines[index] ?? "", sample)) {
        return false;
      }
    }
  }
  return true;
}
