/**
 * Shared constants for QFAI-managed .gitignore block.
 * Used by both `qfai init` (writer) and validators (reader).
 */

import { CANONICAL_TIMESTAMP_GLOB } from "./packLocator.js";

export const QFAI_GITIGNORE_MARKER = "# ── QFAI managed (generated by qfai init) ──";

/**
 * Suffix of every staging directory the atomic `.qfai/state.json` write
 * creates (`core/state.ts`, `<document>.<pid>.<random>.qfai-state.tmp/`).
 * `core/state.ts` builds the names from this constant, so the ignore pattern
 * below and the real names cannot drift.
 */
export const QFAI_STATE_SCRATCH_SUFFIX = ".qfai-state.tmp";

/**
 * The staging directories that write leaves behind when a run is killed
 * between filling the scratch and renaming it over the document.
 *
 * `rename` needs both names on one filesystem, so the staging directory has to
 * sit beside the document it replaces; the next state write sweeps it, but a
 * checkout whose next command never writes state keeps it — and an untracked,
 * half-written state document beside an ignored one is exactly what
 * `git add .` commits by accident. Ignoring the shape is what makes the
 * leftover harmless rather than merely short-lived.
 *
 * Deliberately NOT anchored to `.qfai/`: a `state.json` that is a live symlink
 * is written through to its target (`core/state.ts#prepareWriteTarget`), so the
 * staging directory is created next to THAT file, which an anchored pattern
 * would never cover. Matching on the suffix alone covers every location the
 * write can resolve to inside the repository.
 *
 * `tests/unit/core/stateWritePermissions.test.ts` pins the real staging name
 * against this pattern, for the plain and the symlinked document alike.
 */
export const QFAI_STATE_SCRATCH_IGNORE = `*${QFAI_STATE_SCRATCH_SUFFIX}`;

/**
 * `.qfai/run/` is a leftover path: `qfai workflow` no longer writes it, but a project may still
 * hold one. It stays in the managed ignore block so a leftover never lands in a commit.
 */
export const QFAI_RUN_STATE_IGNORE = ".qfai/run/";

/**
 * The Article XI recommendation, as it is named in a finding's `refs`.
 *
 * Held here rather than written twice: the list below advertises it and
 * {@link missingRecommendedGitignoreEntries} decides it, and those two spellings
 * drifting is how the entry would be advertised and never checked.
 */
export const ARTICLE_XI_TMP_ENTRY = "tmp/";

/**
 * A file directly inside the repository-root staging area Article XI rule 2
 * names — the concrete path the `tmp/` recommendation is a claim about.
 *
 * The recommendation is not "the characters `tmp/` appear somewhere"; it is
 * "scratch work in the root staging area does not reach a commit". A path is
 * what git answers that question about, so it is a path this asks with.
 */
export const ARTICLE_XI_TMP_SAMPLE_PATH = "tmp/scratch.txt";

/**
 * Gitignore entries qfai init writes alongside the marker.
 *
 * Recommended, not required: QFAI-REVIEW-008 reports a missing one at
 * info. A project may legitimately choose to track .qfai/review/** or
 * .qfai/discussion/**, and failing validation for that is the wrong answer.
 * Named for that semantics — the old _REQUIRED_ read as a hard gate this
 * has not been since the severity moved to info.
 */
export const QFAI_GITIGNORE_RECOMMENDED_ENTRIES: readonly string[] = [
  ".qfai/report/*",
  ".qfai/evidence/*",
  ".qfai/discussion/*",
  ".qfai/review/*",
  // Per-runtime state. Written by `qfai discussion use`,
  // `qfai atdd scaffold` (escalation counters), and any future
  // single-file state holder. The file header explicitly states
  // "NOT committed configuration"; without this entry every normal
  // CLI run leaves an untracked `.qfai/state.json` in the consumer
  // repo and makes it trivial to accidentally `git add .` and
  // commit local session pointers / counters.
  ".qfai/state.json",
  // The staging directories that file's atomic write uses; see
  // QFAI_STATE_SCRATCH_IGNORE.
  QFAI_STATE_SCRATCH_IGNORE,
  QFAI_RUN_STATE_IGNORE,
  // Constitution Article XI rule 3: `tmp/` MUST be listed in `.gitignore`.
  // Rule 2 sends every agent's scratch work there, so without the entry the
  // first `git add .` commits exactly what rule 3 exists to prevent.
  //
  // Spelled unanchored because it names the recommendation rather than a line
  // to search for: {@link missingRecommendedGitignoreEntries} decides this one
  // entry by asking whether the file leaves the repository-root staging area
  // ignored, so the anchored `/tmp/` the block writes and a project's own
  // unanchored `tmp/` both satisfy it.
  ARTICLE_XI_TMP_ENTRY,
] as const;

/**
 * Records under `.qfai/` that must stay in version control. `qfai init` writes these negations
 * after the ignore lines so the later pattern wins.
 *
 * Nothing under `.qfai/evidence/` is among them: that directory is a local work area, ignored
 * whole.
 *
 * They are deliberately NOT in `QFAI_GITIGNORE_RECOMMENDED_ENTRIES`: an existing project whose
 * `.gitignore` predates them must not start failing validation.
 */
export const QFAI_GITIGNORE_GOVERNANCE_NEGATIONS: readonly string[] = [
  // Parent re-inclusion. Git cannot re-include a path whose PARENT directory is excluded, so a
  // leaf negation alone is inert against a broad pre-existing `.qfai/` rule an adopting project
  // already had. `!.qfai/` matches the directory only, so the `.qfai/<subtree>/*` ignores above
  // still win for every generated file.
  "!.qfai/",
  // The vendored assistant tree. `!.qfai/` re-includes only the directory, so a broad `.qfai/*`
  // still wins for `.qfai/assistant`, and git never descends into an ignored directory.
  "!.qfai/assistant/",
  // The subtree as well: under a broad `.qfai/**` every descendant is matched in its own right,
  // so re-including the directory re-includes nothing inside it.
  "!.qfai/assistant/**",
] as const;

/**
 * Retired lines that were **renamed** rather than dropped, mapped to their
 * successor.
 *
 * Migration strips every entry of {@link QFAI_GITIGNORE_LEGACY_LINES} and does
 * not re-add recommended ignores a project removed on purpose. A renamed line
 * is the one case where that would take away something the project never gave
 * up: dropping the old discussion ignore without adding the one that replaced
 * it leaves the project with no discussion ignore at all.
 */
export const RETIRED_LINE_SUCCESSORS: Readonly<Record<string, string>> = {
  ".qfai/discussion/discussion-*/": ".qfai/discussion/*",
};

/** Lines removed from the managed block in previous versions; stripped during migration. */
export const QFAI_GITIGNORE_LEGACY_LINES: readonly string[] = [
  "!.qfai/report/README.md",
  "!.qfai/evidence/README.md",
  "!.qfai/discussion/README.md",
  "!.qfai/review/README.md",
  ".qfai/discussion/discussion-*/",
  "!.qfai/review/review-*/",
  "!.qfai/review/review-*/**",
  // Nothing under `.qfai/review/` is tracked, so the two lines that carved an
  // exception out of `.qfai/review/*` are retired with the rest. The leaf was
  // the record naming the packs that predate the strict `revision` form; the
  // directory line above it existed only so that leaf could win, because git
  // cannot re-include a path whose parent is excluded.
  //
  // `.qfai/review/` is a prefix of every other retired line here, and the
  // freshness check asks `existing.includes(entry)` — so a block carrying any
  // of them reports as stale, which is the answer wanted for all of them. It
  // also fires on a negation a project wrote itself under that directory: the
  // rebuild keeps that line, being no retired line of ours, and settles on
  // identical bytes rather than removing it. Inert either way — a negation
  // naming a directory re-includes no file, and `.qfai/review/*` above still
  // decides every path inside.
  "!.qfai/review/.legacy-packs",
  "!.qfai/review/",
  "!.qfai/evidence/decisions/",
  "!.qfai/evidence/decisions/**",
  "!.qfai/decisions/",
  "!.qfai/decisions/**",
  // `.qfai/evidence/` is a local work area, ignored whole by `.qfai/evidence/*`, so every
  // negation that re-included a record under it is retired, and so is the line that re-ignored
  // the prototyping directory those negations opened.
  ".qfai/evidence/prototyping/*",
  "!.qfai/evidence/",
  "!.qfai/evidence/decision/",
  "!.qfai/evidence/decision/**",
  "!.qfai/evidence/prototyping/",
  "!.qfai/evidence/prototyping/grilling.md",
  "!.qfai/evidence/workflow/",
  "!.qfai/evidence/change-request-*.md",
  "!.qfai/evidence/decision-*.md",
  "!.qfai/evidence/implement-*.md",
  "!.qfai/evidence/sdd-*.md",
  `!.qfai/evidence/discussion-${CANONICAL_TIMESTAMP_GLOB}.md`,
  "!.qfai/evidence/atdd-*.md",
  "!.qfai/evidence/import-lite.md",
  `!.qfai/evidence/import-lite-${CANONICAL_TIMESTAMP_GLOB}.md`,
  "!.qfai/evidence/coverage-depth-*.md",
  "!.qfai/evidence/skeleton.md",
  // QFAI keeps no install record, so the negations that kept its two records tracked are retired.
  "!.qfai/install-provenance.json",
  "!.qfai/assistant/.assets.lock.json",
] as const;

export const QFAI_GITIGNORE_BLOCK = [
  QFAI_GITIGNORE_MARKER,
  ".qfai/report/*",
  ".qfai/evidence/*",
  ".qfai/discussion/*",
  ".qfai/review/*",
  // The archive location review packs were moved to before the current layout
  // put them under `.qfai/review/` itself, where the line above already covers
  // them. Nothing writes this path now, so a fresh project never grows one; it
  // is here for a project that still carries the directory, whose packs are
  // review artifacts under any name.
  //
  // Deliberately absent from QFAI_GITIGNORE_RECOMMENDED_ENTRIES: a project
  // whose `.gitignore` predates this line must not start failing validation
  // over a directory QFAI no longer writes.
  ".qfai/review_archive/*",
  ".qfai/state.json",
  QFAI_STATE_SCRATCH_IGNORE,
  // The advisory lock that serializes writes to the file above. It sits
  // beside it so that everyone who may write the state may also reap a lock
  // left behind by a crash — which a lock in the OS temp dir, owned by
  // whichever user got there first, does not allow on a shared checkout.
  // Deliberately absent from QFAI_GITIGNORE_RECOMMENDED_ENTRIES: a project
  // whose `.gitignore` predates this line must not start failing validation
  // over it.
  ".qfai/state.json.lock",
  QFAI_RUN_STATE_IGNORE,
  // Article XI rule 3, the one mandated ignore that is not under `.qfai/`.
  // Anchored: rule 2 names the repository-root staging area, and an unanchored
  // `tmp/` would also swallow a `src/**/tmp/` a project tracks on purpose.
  "/tmp/",
  // Negations last: git applies the last matching pattern, so these re-include
  // the governance records the ignores above would otherwise swallow.
  ...QFAI_GITIGNORE_GOVERNANCE_NEGATIONS,
  "",
].join("\n");

/**
 * True when `pattern` — one ignore line — could match `samplePath`.
 *
 * A presence check is not enough for a negation: git applies the **last**
 * matching pattern, so a negation is effective only when no ignore line below
 * it matches the same path. Deciding that needs real gitignore glob semantics,
 * not a prefix comparison — a prefix test cannot see that `*.json` or
 * `**` + `/*.json`, placed after `!.qfai/assistant/**`,
 * re-ignores exactly what the negation re-included.
 *
 * Implemented rules, the ones a real `.gitignore` uses:
 *
 * - a leading `/`, or any `/` before the final character, anchors the pattern
 *   to the file's directory; otherwise it matches at any depth;
 * - a trailing `/` names a directory, and a directory pattern also covers
 *   everything beneath it;
 * - the double-star form crosses `/`, a single `*` does not, and `?` matches
 *   one non-`/` character;
 * - `[0-9]`, `[!a-z]` and `[[:digit:]]` are character classes, not the literal
 *   brackets a blanket escape turned them into.
 *
 * Blank lines, comments and negations are not ignore lines and never match.
 */
export function gitignorePatternMatches(pattern: string, samplePath: string): boolean {
  const trimmed = pattern.trim();
  if (trimmed.length === 0 || trimmed.startsWith("#") || trimmed.startsWith("!")) {
    return false;
  }
  return patternMatches(trimmed, samplePath, true);
}

/**
 * The same match, for the body of a negation.
 *
 * A directory pattern covers everything beneath it when it **ignores**, because
 * git never descends into an excluded directory. A negation cannot work the
 * same way: gitignore(5) says it is not possible to re-include a file whose
 * parent directory is excluded. `!.qfai/` re-includes the directory entry and
 * nothing under it.
 *
 * Read as a subtree, one such line cancelled every ignore above it and sat last,
 * so the verdict came back "not ignored" for paths git ignores — and the caller
 * that warns about an ignored governance record stayed silent in the one
 * configuration it exists for.
 *
 * Only the trailing-slash form narrows. `!a/**` says descendants in its own
 * text, and a negation naming a file has none. Excluding an ancestor is not
 * this function's job either: {@link isPathIgnoredByLayers} judges each ancestor
 * prefix before the path itself, which is where "git never descends" belongs.
 */
function negationBodyMatches(body: string, samplePath: string): boolean {
  return patternMatches(body, samplePath, !body.trim().endsWith("/"));
}

/**
 * One gitignore pattern against one path.
 *
 * `coversDescendants` is the difference between the two callers above: an
 * ignore line reaches into the directory it names, a negation does not.
 */
function patternMatches(pattern: string, samplePath: string, coversDescendants: boolean): boolean {
  const trimmed = pattern.trim();
  const withoutTrailingSlash = trimmed.endsWith("/") ? trimmed.slice(0, -1) : trimmed;
  // Per gitignore(5): a `/` anywhere but the end anchors the pattern.
  const anchored = withoutTrailingSlash.includes("/");
  const body = withoutTrailingSlash.replace(/^\//, "");
  if (body.length === 0) {
    return false;
  }

  const source = globToRegexSource(body);
  if (source === null) {
    return false;
  }

  // The trailing group is what makes a directory pattern cover its contents.
  const prefix = anchored ? "^" : "^(?:.*/)?";
  const suffix = coversDescendants ? "(?:/.*)?$" : "$";
  return new RegExp(`${prefix}${source}${suffix}`).test(samplePath.replace(/^\//, ""));
}

/** One literal character, safe to drop into a regular expression. */
function escapeLiteral(char: string): string {
  return /[.*+?^${}()|[\]\\]/.test(char) ? `\\${char}` : char;
}

/** One literal character, safe to drop inside a regular-expression class. */
function escapeInClass(char: string): string {
  return /[\]\\^]/.test(char) ? `\\${char}` : char;
}

/**
 * POSIX class names git's wildmatch accepts, as regular-expression class bodies.
 *
 * Measured, not assumed: `git check-ignore -v` names
 * `coverage-depth-spec-[[:digit:]]*.md` as the rule that ignores
 * `coverage-depth-spec-0001.md`.
 */
const POSIX_CLASSES: Readonly<Record<string, string>> = {
  alnum: "A-Za-z0-9",
  alpha: "A-Za-z",
  blank: " \\t",
  cntrl: "\\x00-\\x1f\\x7f",
  digit: "0-9",
  graph: "\\x21-\\x7e",
  lower: "a-z",
  print: "\\x20-\\x7e",
  punct: "!-/:-@\\[-`{-~",
  space: " \\t\\n\\r\\f\\v",
  upper: "A-Z",
  xdigit: "0-9A-Fa-f",
};

/**
 * One `[...]` bracket expression as a regular-expression class, or `null`.
 *
 * git matches these the way fnmatch does — a set, a range, a `!`- or
 * `^`-negated set, and the POSIX `[:digit:]` names — so escaping `[` and `]`
 * into literals made `.qfai/evidence/coverage-depth-spec-[0-9]*.md` a line
 * `git check-ignore -v` reports as the winner and this matcher reported as no
 * match at all. `null` is an unterminated `[`, which wildmatch aborts on: git
 * ignores nothing for such a line, and neither does this.
 *
 * No wildcard crosses `/` under `FNM_PATHNAME`, and a class such as `[!a]` or
 * `[.-9]` spans it, so the lookahead holds the separator out of every one.
 */
function bracketExpression(glob: string, open: number): { source: string; next: number } | null {
  let index = open + 1;
  const negated = glob[index] === "!" || glob[index] === "^";
  if (negated) {
    index += 1;
  }
  let body = "";
  while (index < glob.length) {
    const char = glob[index] ?? "";
    // A `]` before any content is that character, not the terminator.
    if (char === "]" && body.length > 0) {
      return { source: `(?!/)[${negated ? "^" : ""}${body}]`, next: index + 1 };
    }
    if (glob.startsWith("[:", index)) {
      const close = glob.indexOf(":]", index + 2);
      const named = close === -1 ? undefined : POSIX_CLASSES[glob.slice(index + 2, close)];
      if (named === undefined) {
        return null;
      }
      body += named;
      index = close + 2;
      continue;
    }
    if (char === "\\" && index + 1 < glob.length) {
      body += escapeInClass(glob[index + 1] ?? "");
      index += 2;
      continue;
    }
    // `-` is left bare: inside a class it is the range operator.
    body += char === "-" ? "-" : escapeInClass(char);
    index += 1;
  }
  return null;
}

/**
 * One gitignore glob as a regular-expression source, or `null` when no path
 * can match it.
 *
 * A scan rather than chained replacements, because a bracket expression is the
 * one construct whose contents obey a different alphabet from the text around
 * it — the `*` in `[*a]` is a literal asterisk and the `.` in `[.-9]` is a
 * range endpoint — and a blanket escape-then-replace pass cannot tell which
 * half of the pattern it is standing in.
 */
function globToRegexSource(glob: string): string | null {
  let source = "";
  let index = 0;
  while (index < glob.length) {
    const char = glob[index] ?? "";
    if (glob.startsWith("**/", index)) {
      source += "(?:.*/)?";
      index += 3;
      continue;
    }
    if (glob.startsWith("**", index)) {
      source += ".*";
      index += 2;
      continue;
    }
    if (char === "*" || char === "?") {
      source += char === "*" ? "[^/]*" : "[^/]";
      index += 1;
      continue;
    }
    if (char === "[") {
      const bracket = bracketExpression(glob, index);
      if (bracket === null) {
        return null;
      }
      source += bracket.source;
      index = bracket.next;
      continue;
    }
    // A backslash quotes the next character: git reads `\*` as an asterisk.
    if (char === "\\" && index + 1 < glob.length) {
      source += escapeLiteral(glob[index + 1] ?? "");
      index += 2;
      continue;
    }
    source += escapeLiteral(char);
    index += 1;
  }
  return source;
}

/**
 * One `.gitignore` file, with the directory whose subtree it governs.
 *
 * `dir` is repo-relative, POSIX-separated, and `""` for the file at the
 * repository root. Its patterns are written relative to that directory, which
 * is why the layer has to carry it: a bare `*` inside
 * `.qfai/evidence/.gitignore` excludes that directory's contents, not the whole
 * repository.
 */
export type GitignoreLayer = {
  dir: string;
  lines: readonly string[];
};

/**
 * True when `layers` — every `.gitignore` on the way down to `samplePath` —
 * leave it ignored.
 *
 * Two precedence rules, only the second of which a single root-file read got
 * right:
 *
 * - **the deepest file that matches wins.** Per gitignore(5), patterns read
 *   from a `.gitignore` deeper in the tree override those from a shallower one,
 *   so on an adopting project that carries nested ignore files the root managed
 *   block is not the last word in either direction: a nested negation
 *   re-includes a path the root ignored, and a nested re-ignore hides one the
 *   root re-included.
 * - **within one file the last matching pattern wins**, negations included.
 *
 * Ancestors are decided first because git never descends into an excluded
 * directory — a negation on a file inside one is unreachable. A layer deeper
 * than the path being judged cannot contain it, so
 * the same walk also declines to read an ignore file git would never have
 * reached.
 *
 * `samplePath` is repo-relative and POSIX-separated.
 */
export function isPathIgnoredByLayers(
  layers: readonly GitignoreLayer[],
  samplePath: string,
): boolean {
  const normalized = samplePath.replace(/^\//, "");
  const segments = normalized.split("/").filter((segment) => segment.length > 0);
  const ordered = [...layers].sort((left, right) => layerDepth(left.dir) - layerDepth(right.dir));
  for (let depth = 1; depth < segments.length; depth += 1) {
    // No trailing slash: `.qfai/evidence/*` matches `.qfai/evidence/` — the
    // directory's own contents-pattern would otherwise read as excluding the
    // directory it exists to keep walkable.
    if (layeredVerdict(ordered, segments.slice(0, depth).join("/"))) {
      return true;
    }
  }
  return layeredVerdict(ordered, normalized);
}

/**
 * True when `lines` — one root-level `.gitignore` — leave `samplePath` ignored.
 *
 * The single-file case of {@link isPathIgnoredByLayers}. A caller that can meet
 * a project carrying nested ignore files has to use that one instead.
 */
export function isPathIgnored(lines: readonly string[], samplePath: string): boolean {
  return isPathIgnoredByLayers([{ dir: "", lines }], samplePath);
}

/** Directory nesting depth; the repository root (`""`) is 0. */
function layerDepth(dir: string): number {
  return dir.split("/").filter((segment) => segment.length > 0).length;
}

/** Deepest-matching-file-wins over one concrete path, each file answering only for its own subtree. */
function layeredVerdict(layers: readonly GitignoreLayer[], samplePath: string): boolean {
  let ignored = false;
  for (const layer of layers) {
    const dir = layer.dir.replace(/^\/+/, "").replace(/\/+$/, "");
    const prefix = dir.length === 0 ? "" : `${dir}/`;
    if (prefix.length > 0 && !samplePath.startsWith(prefix)) {
      continue;
    }
    const verdict = lastMatchVerdict(layer.lines, samplePath.slice(prefix.length));
    // `undefined` is "this file said nothing", which must not overwrite what a
    // shallower one decided; only a real match moves the standing verdict.
    if (verdict !== undefined) {
      ignored = verdict;
    }
  }
  return ignored;
}

/**
 * Last-pattern-wins over one concrete path; negations count as matches.
 *
 * `undefined` when no pattern in the file matched at all — distinct from
 * `false`, which is a negation actively re-including the path and therefore
 * something that must outrank whatever a shallower file said.
 */
function lastMatchVerdict(lines: readonly string[], samplePath: string): boolean | undefined {
  let verdict: boolean | undefined;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed.startsWith("#")) {
      continue;
    }
    const negated = trimmed.startsWith("!");
    // `gitignorePatternMatches` refuses a `!` line by design, so the negation is
    // matched on its body and its verdict inverted. Through
    // `negationBodyMatches`, which does not read a trailing slash as a subtree:
    // a negation re-includes the directory entry, never what a parent's
    // exclusion already put out of reach.
    const matched = negated
      ? negationBodyMatches(trimmed.slice(1), samplePath)
      : gitignorePatternMatches(trimmed, samplePath);
    if (!matched) {
      continue;
    }
    verdict = !negated;
  }
  return verdict;
}

/**
 * True when `lines` leave `samplePath` ignored, under git's own last-match rule.
 *
 * The whole file is walked and every matching line — ignore or negation — moves
 * the verdict, because git's answer is the LAST pattern that matches and not the
 * first. A presence test cannot produce that answer: `!/tmp/` placed after the
 * managed block contains the characters of the entry it cancels.
 *
 * Comments and blank lines are not patterns and never move the verdict, which is
 * the other half of why a text search is the wrong instrument here — a sentence
 * of prose mentioning a path is not an ignore of it.
 */
export function effectivelyIgnores(lines: readonly string[], samplePath: string): boolean {
  let ignored = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed.startsWith("#")) {
      continue;
    }
    const negated = trimmed.startsWith("!");
    // `gitignorePatternMatches` refuses a negation by design, so the `!` comes
    // off here and the verdict it sets is what carries the negation's meaning.
    const body = negated ? trimmed.slice(1) : trimmed;
    if (!gitignorePatternMatches(body, samplePath)) {
      continue;
    }
    ignored = !negated;
  }
  return ignored;
}

/**
 * The recommended entries `content` does not satisfy, for `QFAI-REVIEW-008`.
 *
 * One function because two readings of "satisfied" would drift. The `.qfai/**`
 * entries are literal paths under a directory QFAI owns, and a project that
 * ignores one from its own section satisfies the recommendation just as well —
 * so containment is the right question for them, and reporting a rule the author
 * already has would only push them to duplicate it.
 *
 * {@link ARTICLE_XI_TMP_ENTRY} is not like that, and containment answers the
 * wrong question for it. The entry is spelled unanchored while the block writes
 * the anchored `/tmp/`, so the substring `tmp/` is also inside a project's own
 * `src/tmp/` — a directory Article XI makes no claim about — inside prose that
 * merely mentions `tmp/`, and inside a later `!/tmp/` that cancels the ignore
 * outright. In all three the root staging area is still tracked while the notice
 * that exists to say so is suppressed. So this entry is decided by asking git's
 * question — is {@link ARTICLE_XI_TMP_SAMPLE_PATH} ignored once the whole file
 * has had its say — which both spellings of a real ignore still answer yes to.
 */
export function missingRecommendedGitignoreEntries(content: string): string[] {
  const lines = content.split(/\r?\n/);
  return QFAI_GITIGNORE_RECOMMENDED_ENTRIES.filter((entry) =>
    entry === ARTICLE_XI_TMP_ENTRY
      ? !effectivelyIgnores(lines, ARTICLE_XI_TMP_SAMPLE_PATH)
      : !content.includes(entry),
  );
}

/**
 * A concrete path the negation re-includes, for feeding
 * {@link gitignorePatternMatches}.
 *
 * A negation is itself a glob, and glob-vs-glob overlap has no cheap exact answer. The two
 * directions of error are NOT symmetric: a false "conflict" only re-appends a negation that was
 * already last, which is where it belongs anyway — but a MISSED conflict leaves a file git is
 * ignoring outside version control, with nothing to notice it afterwards.
 *
 * So the caller instantiates BOTH patterns and asks the question both ways round; see
 * {@link negationsOutrankLaterIgnores}.
 */
export function negationSamplePath(negation: string): string {
  const body = negation.replace(/^!/, "");
  const withContents = body.endsWith("/") ? `${body}sample` : body;
  // A scan rather than chained replacements, for the reason `globToRegexSource`
  // gives: inside a bracket expression the alphabet is different, and the same
  // parser has to read it. Left as text, `[0-9]` instantiates as the four
  // characters `[0-9]` — a path no rule written about digits matches, so every
  // overlap question about a stamped negation would answer "no" and a later
  // `record-[0-9]*.md` would look like no conflict at all.
  let sample = "";
  let index = 0;
  while (index < withContents.length) {
    const char = withContents[index] ?? "";
    if (char === "[") {
      const bracket = bracketExpression(withContents, index);
      if (bracket !== null) {
        sample += sampleForClass(bracket.source, withContents.slice(index, bracket.next));
        index = bracket.next;
        continue;
      }
      // An unterminated `[`. git ignores nothing for such a line, so there is
      // nothing to instantiate: the character stands for itself.
    }
    if (withContents.startsWith("**", index)) {
      sample += "sample/leaf";
      index += 2;
      continue;
    }
    if (char === "*") {
      sample += "sample";
      index += 1;
      continue;
    }
    if (char === "?") {
      sample += "s";
      index += 1;
      continue;
    }
    sample += char;
    index += 1;
  }
  return sample;
}

/** Characters tried against a bracket expression, in the order they are tried. */
const CLASS_SAMPLE_CANDIDATES = ["0", "a", "z", "9", "-", "_"];

/**
 * One character a bracket expression accepts, or `literal` when none is found.
 *
 * Tried against a short alphabet rather than solved: `source` is already the
 * class as a regular expression, so a candidate it matches is a member under
 * the same reading `gitignorePatternMatches` uses. Keeping the literal spelling
 * for a class no candidate satisfies leaves the caller where it was rather than
 * handing it a path the negation does not re-include.
 */
function sampleForClass(source: string, literal: string): string {
  let matcher: RegExp;
  try {
    matcher = new RegExp(`^(?:${source})$`);
  } catch {
    return literal;
  }
  return CLASS_SAMPLE_CANDIDATES.find((candidate) => matcher.test(candidate)) ?? literal;
}

/**
 * True when every one of `negations` is still the last word on the paths it
 * re-includes.
 *
 * `lines` is the whole file, not one block: a project that appended
 * `.qfai/*.json` **after** the managed block wins under git's
 * last-match rule, and a block-scoped check calls the negation effective while
 * `git check-ignore -v` names the project's line.
 */
export function negationsOutrankLaterIgnores(
  lines: readonly string[],
  negations: readonly string[],
): boolean {
  for (const negation of negations) {
    const at = lines.lastIndexOf(negation);
    if (at === -1) {
      return false;
    }
    const sample = negationSamplePath(negation);
    const negationBody = negation.replace(/^!/, "");
    for (let index = at + 1; index < lines.length; index += 1) {
      const later = lines[index] ?? "";

      // Direction 1: a path this negation re-includes, matched by the later ignore.
      if (gitignorePatternMatches(later, sample)) {
        return false;
      }

      // Direction 2: a path the later ignore covers, matched by this negation.
      //
      // Direction 1 alone decides overlap from ONE instance of the negation, and two globs can
      // overlap without that instance being in the intersection: a negation `!docs/record-*.md`
      // instantiates as `record-sample.md`, and a later line `docs/record-spec-*.md` does not
      // match it — while a real record whose name carries a spec number is matched by both.
      // Missing that overlap would leave a record the negation exists to keep in version control
      // ignored, with nothing left to flag it.
      //
      // Instantiating the LATER pattern and asking whether the negation covers it closes that
      // case: `record-spec-sample.md` is matched by `record-*.md`. Neither
      // direction alone is exact, and two are not exact either — but each one can only ADD
      // conflicts, and a false conflict costs a relocation that was harmless anyway.
      const trimmed = later.trim();
      if (trimmed.length === 0 || trimmed.startsWith("#") || trimmed.startsWith("!")) {
        continue;
      }
      if (gitignorePatternMatches(negationBody, negationSamplePath(trimmed))) {
        return false;
      }
    }
  }
  return true;
}
