/**
 * Meta-test: a runtime message names no launcher.
 *
 * A running qfai does not know which entry point started it (an `npx` prefix,
 * a package script or a global bin), so a message naming one launcher is wrong
 * for the other two. The validate contract states the spelling; this test holds
 * `src/**` to it. Shipped docs take the opposite rule, enforced by
 * `canonicalQfaiLauncher.test.ts`.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  listSourceFiles,
  relativeToPosix,
  stripComments,
} from "../helpers/typescriptSourceScan.js";

import { parseContractRules } from "../../src/core/storyTree/contractRules.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PACKAGE_ROOT = path.resolve(__dirname, "../..");
const SRC_DIR = path.join(PACKAGE_ROOT, "src");
const REPO_ROOT = path.resolve(PACKAGE_ROOT, "../..");
const VALIDATE_CONTRACT_MD = path.join(
  REPO_ROOT,
  ".qfai",
  "spec",
  "03_contract",
  "cli",
  "cli-0014-qfai-validate.md",
);

// QFAI:EX-0001-0039-08
describe("runtime message launcher", () => {
  it("keeps the launcher out of a runtime message, and in the validate contract", async () => {
    const spelling = parseContractRules(
      VALIDATE_CONTRACT_MD,
      await readFile(VALIDATE_CONTRACT_MD, "utf-8"),
    ).rules.find((rule) => rule.statement.includes("A runtime message spells a command"));
    expect(spelling, "the validate contract states the command spelling as a rule").toBeDefined();
    expect(spelling?.statement).toContain("`npx qfai <subcommand>`");
    expect(spelling?.statement).toContain("`qfai <subcommand>`");

    // Comments explain the implementation and are not read by an operator, so
    // they are removed first. A line-start test cannot do it: `emit(msg); //
    // npx qfai validate` is a comment on a code line. Stripping replaces a
    // comment with spaces, so the line numbers below still point at the source.
    const files = await listSourceFiles(SRC_DIR);
    expect(files.length, `no sources found under ${SRC_DIR}`).toBeGreaterThan(0);

    const offenders: string[] = [];
    for (const file of files) {
      const source = await readFile(file, "utf-8");
      // Stripping only removes text, so a file without `npx qfai ` cannot
      // produce an offender; skipping it saves the lexing.
      if (!source.includes("npx qfai ")) {
        continue;
      }
      const rel = relativeToPosix(SRC_DIR, file);
      stripComments(source)
        .split(/\r?\n/)
        .forEach((line, index) => {
          // The generated-file header is documentation in the reader's tree,
          // so it takes the documentation rule. It survives the strip: it is
          // a `#` comment inside a TypeScript string, not a TypeScript one.
          if (!line.includes("npx qfai ") || line.includes("# Generated by")) {
            return;
          }
          offenders.push(`${rel}:${index + 1}`);
        });
    }

    expect(offenders, "runtime message naming a launcher").toEqual([]);
  });
});
